name: Enhanced Pipeline and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  enhanced-pipeline-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directories
      run: |
        mkdir -p data/archive
        mkdir -p data/processed
        mkdir -p data/raw
        mkdir -p dashboard/data
        
    - name: Run wildlife job scraper
      run: |
        python wildlife_job_scraper.py
      continue-on-error: true
      
    - name: Run enhanced analysis
      run: |
        if [ -f "src/analysis/enhanced_analysis.py" ]; then
          python src/analysis/enhanced_analysis.py
        fi
      continue-on-error: true
      
    - name: Generate dashboard data
      run: |
        if [ -f "src/analysis/enhanced_dashboard_data.py" ]; then
          python src/analysis/enhanced_dashboard_data.py
        fi
      continue-on-error: true
      
    - name: Copy data to dashboard directory
      run: |
        # Copy data files to dashboard directory for deployment
        if [ -f "data/enhanced_data.json" ]; then
          cp data/enhanced_data.json dashboard/data/
        fi
        if [ -f "data/historical_positions.json" ]; then
          cp data/historical_positions.json dashboard/data/
        fi
        if [ -f "data/processed/verified_graduate_assistantships.json" ]; then
          cp data/processed/verified_graduate_assistantships.json dashboard/data/
        fi
        
    - name: Setup GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3
      
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./dashboard
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v2
      
    - name: Archive data with timestamp
      if: github.ref == 'refs/heads/main'
      run: |
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        
        # Archive enhanced data
        if [ -f "data/enhanced_data.json" ]; then
          cp data/enhanced_data.json "data/archive/enhanced_${TIMESTAMP}.json"
        fi
        
        # Archive historical positions
        if [ -f "data/historical_positions.json" ]; then
          cp data/historical_positions.json "data/archive/historical_positions_${TIMESTAMP}.json"
        fi
        
        # Archive verified graduate assistantships
        if [ -f "data/processed/verified_graduate_assistantships.json" ]; then
          cp data/processed/verified_graduate_assistantships.json "data/archive/verified_grad_${TIMESTAMP}.json"
        fi
        
    - name: Commit and push changes
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/ dashboard/data/ || true
        git commit -m "Automated data update - $(date +"%Y-%m-%d %H:%M:%S")" || exit 0
        git push || true

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false