name: Weekly Job Scraper

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upgrade pip and setuptools
      run: pip install --upgrade pip setuptools

    - name: Install dependencies
      run: |
        for i in 1 2 3; do pip install -r requirements.txt && break || sleep 10; done
    
    - name: Check Internet Connection
        run: curl -I https://example.com

    - name: Run Scraper
      run: python main.py
    
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions@github.com"
        git add job_data.csv
        git commit -m "Automated job data update [skip ci]" || echo "No changes to commit"
        git push