name: Wildlife Jobs Scraper

on:
  schedule:
    # Weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual trigger
  
jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data archive directory
      run: mkdir -p data/archive
      
    - name: Run wildlife job scraper
      run: |
        python wildlife_job_scraper.py
        
    - name: Generate enhanced analysis
      run: |
        python scripts/enhanced_analysis.py
        
    - name: Generate dashboard data
      run: |
        python scripts/enhanced_dashboard_data.py
        
    - name: Archive data with timestamp
      run: |
        timestamp=$(date +"%Y%m%d_%H%M%S")
        cp data/graduate_assistantships.json "data/archive/jobs_${timestamp}.json"
        cp data/graduate_assistantships.csv "data/archive/jobs_${timestamp}.csv"
        cp data/historical_positions.json "data/archive/historical_${timestamp}.json"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Weekly job scrape - $(date +'%Y-%m-%d %H:%M UTC')"
          git push
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dashboard
        publish_branch: gh-pages
        force_orphan: true